# Generated by Django 4.2.29 on 2026-03-17 17:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('es_inversion', models.BooleanField(default=False, help_text='Si es True, los movimientos de esta categoría se contabilizan como patrimonio y quedan excluidos del cálculo de gastos corrientes.')),
            ],
            options={
                'verbose_name_plural': 'categorías',
            },
        ),
        migrations.CreateModel(
            name='CuentaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Personal', 'Arquitecto'", max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('visible_familia', models.BooleanField(default=False, help_text='Si es True, los miembros de la familia pueden ver los movimientos de esta cuenta. Por defecto es privada.')),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número de cuota (1, 2, 3... N).')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mes_facturacion', models.DateField(help_text="Primer día del mes en que esta cuota debe aparecer en el estado de cuenta. Se usa para filtrar cuotas por período en la vista 'Pagar tarjeta'.")),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FACTURADO', 'Facturado'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=10)),
                ('incluir', models.BooleanField(default=True, help_text='Si es False, esta cuota queda excluida del pago del mes actual y su mes_facturacion se mueve al mes siguiente (prorrateo manual).')),
            ],
            options={
                'ordering': ['mes_facturacion', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='IngresoComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Primer día del mes al que corresponde este ingreso.')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('origen', models.CharField(blank=True, help_text="Descripción del origen del ingreso. Ej: 'Sueldo', 'Honorarios', 'Arriendo'.", max_length=100)),
            ],
            options={
                'ordering': ['-mes'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('ambito', models.CharField(choices=[('PERSONAL', 'Personal'), ('COMUN', 'Común')], help_text='PERSONAL: visible solo para el usuario. COMUN: visible para toda la familia y se incluye en la liquidación mensual.', max_length=10)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('oculto', models.BooleanField(default=False, help_text='Si es True, el movimiento no aparece en los listados normales. Útil para ocultar movimientos sensibles sin eliminarlos.')),
                ('num_cuotas', models.IntegerField(blank=True, help_text='Número de cuotas. Obligatorio si el pago es con crédito.', null=True)),
                ('monto_cuota', models.DecimalField(blank=True, decimal_places=2, help_text='Valor de cada cuota. Si no se ingresa, el sistema calcula monto / num_cuotas. La diferencia de centavos va a la primera cuota.', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Primer día del mes al que aplica este presupuesto.')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Visa BCI', 'Mastercard Santander'", max_length=100)),
                ('banco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TutorCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(help_text='Cuenta personal tutelada. Pertenece a otro usuario.', on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='finanzas.cuentapersonal')),
            ],
            options={
                'verbose_name': 'tutoría de cuenta',
                'verbose_name_plural': 'tutorías de cuentas',
            },
        ),
    ]
