# Generated by Django 4.2.29 on 2026-03-17 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('viajes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorcuenta',
            name='tutor',
            field=models.ForeignKey(help_text='Usuario que ejerce la tutoría. Ve y puede operar esta cuenta.', on_delete=django.db.models.deletion.CASCADE, related_name='tutelas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='usuario',
            field=models.ForeignKey(help_text='Propietario de la tarjeta. Solo este usuario puede usarla al registrar movimientos.', on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='finanzas.categoria'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='usuarios.familia'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Si es null, el presupuesto aplica a toda la familia. Si tiene valor, es un presupuesto personal del usuario.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='categoria',
            field=models.ForeignKey(help_text='Categoría del movimiento. PROTECT evita borrar categorías con movimientos asociados.', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.categoria'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cuenta',
            field=models.ForeignKey(blank=True, help_text='Cuenta personal opcional. Si se asigna, el movimiento se agrupa bajo ese contexto financiero del usuario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='finanzas.cuentapersonal'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='familia',
            field=models.ForeignKey(help_text='Familia a la que pertenece este movimiento. Todos los filtros de vistas parten por este campo.', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='usuarios.familia'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.metodopago'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tarjeta',
            field=models.ForeignKey(blank=True, help_text="Obligatorio si metodo_pago.tipo == 'CREDITO'. El signal de post_save valida esta condición antes de generar cuotas.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='finanzas.tarjeta'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que registró el movimiento.', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='viaje',
            field=models.ForeignKey(blank=True, help_text='Si el movimiento ocurre durante un viaje activo, se asocia aquí para el seguimiento de presupuesto vs. gasto real del viaje.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='viajes.viaje'),
        ),
        migrations.AddField(
            model_name='ingresocomun',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_comunes', to='usuarios.familia'),
        ),
        migrations.AddField(
            model_name='ingresocomun',
            name='usuario',
            field=models.ForeignKey(help_text='Miembro que reporta este ingreso. Cada uno ingresa el suyo.', on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_comunes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuota',
            name='movimiento',
            field=models.ForeignKey(help_text='Movimiento de origen. Si se elimina el movimiento, todas sus cuotas se eliminan en cascada.', on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='finanzas.movimiento'),
        ),
        migrations.AddField(
            model_name='cuentapersonal',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario dueño de esta cuenta personal.', on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria',
            name='familia',
            field=models.ForeignKey(blank=True, help_text='Si es null, la categoría es global del sistema.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='usuarios.familia'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Si es null, la categoría es compartida en la familia. Si tiene valor, es privada de este usuario.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_personales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tutorcuenta',
            unique_together={('tutor', 'cuenta')},
        ),
        migrations.AlterUniqueTogether(
            name='presupuesto',
            unique_together={('familia', 'usuario', 'categoria', 'mes')},
        ),
        migrations.AlterUniqueTogether(
            name='cuota',
            unique_together={('movimiento', 'numero')},
        ),
    ]
