# Generated by Django 4.2.29 on 2026-03-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_ingresocomun_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='dia_facturacion',
            field=models.IntegerField(blank=True, help_text='Día del mes en que cierra el ciclo de facturación (1-31).', null=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='dia_vencimiento',
            field=models.IntegerField(blank=True, help_text='Día del mes en que vence el pago (1-31).', null=True),
        ),
    ]
