# Generated by Django 4.2.29 on 2026-03-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_saldos_y_liquidacion_snapshots'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='liquidacioncomunmensualsnapshot',
            new_name='finanzas_li_familia_981e0a_idx',
            old_name='finanzas_li_familia_9a1c2e_idx',
        ),
        migrations.RenameIndex(
            model_name='saldomensualsnapshot',
            new_name='finanzas_sa_familia_c3e9f3_idx',
            old_name='finanzas_sa_familia_6e8b9d_idx',
        ),
    ]
