# Generated by Django 4.2.29 on 2026-03-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0010_saldo_mensual_ingresos_egresos'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='resumenhistoricomessnapshot',
            new_name='finanzas_re_familia_269404_idx',
            old_name='finanzas_re_familia_6a8b2c_idx',
        ),
    ]
