# Generated by Django 4.2.29 on 2026-03-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0012_sueldo_estimado_prorrateo_mensual'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sueldoestimadoprorrateomensual',
            new_name='finanzas_su_usuario_2c4b70_idx',
            old_name='finanzas_su_usuario_0a1b2c_idx',
        ),
        migrations.AlterField(
            model_name='saldomensualsnapshot',
            name='egresos_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma de egresos corrientes en efectivo/débito (sin crédito, sin categoría inversión).', max_digits=14),
        ),
        migrations.AlterField(
            model_name='saldomensualsnapshot',
            name='ingresos_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma de ingresos en efectivo/débito (sin crédito, sin ingreso declarado fondo común/sueldo).', max_digits=14),
        ),
    ]
