# Generated by Django 4.2.29 on 2026-03-31 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0013_rename_finanzas_su_usuario_0a1b2c_idx_finanzas_su_usuario_2c4b70_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, help_text='Categoría padre para agrupar subcategorías.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='finanzas.categoria'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='cuenta_personal',
            field=models.ForeignKey(blank=True, help_text='Cuenta personal opcional para categorías privadas del usuario. Permite filtrar categorías personales por cuenta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='finanzas.cuentapersonal'),
        ),
    ]
