# Generated by Django 4.2.30 on 2026-07-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0003_drive_oauth_fields'),
        ('finanzas', '0017_familia_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresocomun',
            name='espacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='espacios.espacio'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='espacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='espacios.espacio'),
        ),
    ]
