# Generated by Django 4.2.30 on 2026-07-13 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0004_remove_espacio_familia_origen'),
        ('finanzas', '0020_cutover_remove_familia'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='liquidacioncomunmensualsnapshot',
            new_name='finanzas_li_espacio_aa9a34_idx',
            old_name='finanzas_li_espacio_mes_idx',
        ),
        migrations.RenameIndex(
            model_name='resumenhistoricomessnapshot',
            new_name='finanzas_re_espacio_ecd767_idx',
            old_name='finanzas_re_espacio_mes_idx',
        ),
        migrations.RenameIndex(
            model_name='saldomensualsnapshot',
            new_name='finanzas_sa_espacio_6fa019_idx',
            old_name='finanzas_sa_espacio_usuario_mes_idx',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='espacio',
            field=models.ForeignKey(blank=True, help_text='Tenant del espacio. Null para categorías globales del sistema.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='espacios.espacio'),
        ),
    ]
