# Generated by Django 4.2.30 on 2026-07-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0022_cambio_compensacion_notificaciones'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cambiocompensacionmensual',
            new_name='finanzas_ca_espacio_35eb0b_idx',
            old_name='finanzas_ca_espacio_8f2a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='cambiocompensacionmensual',
            new_name='finanzas_ca_creado__c0a4f2_idx',
            old_name='finanzas_ca_creado__4e7c2d_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacionusuario',
            new_name='finanzas_no_usuario_50fc4d_idx',
            old_name='finanzas_no_usuario_9a3f44_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacionusuario',
            new_name='finanzas_no_espacio_c1ef0f_idx',
            old_name='finanzas_no_espacio_1b8e55_idx',
        ),
    ]
