# Generated by Django 4.2.30 on 2026-07-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0025_brechaconsultaasistente'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='brechaconsultaasistente',
            new_name='finanzas_br_senal_df91ef_idx',
            old_name='finanzas_br_senal_8a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='brechaconsultaasistente',
            new_name='finanzas_br_intento_47652b_idx',
            old_name='finanzas_br_intento_9d3e4f_idx',
        ),
        migrations.RenameIndex(
            model_name='brechaconsultaasistente',
            new_name='finanzas_br_espacio_699fdd_idx',
            old_name='finanzas_br_espacio_0a5b6c_idx',
        ),
    ]
