# Generated by Django 4.2.30 on 2026-07-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0027_captura_movimientos_pendientes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='codigovinculocaptura',
            new_name='finanzas_co_codigo_a9de0d_idx',
            old_name='finanzas_co_codigo_9f0a1d_idx',
        ),
        migrations.RenameIndex(
            model_name='codigovinculocaptura',
            new_name='finanzas_co_usuario_d4c5d2_idx',
            old_name='finanzas_co_usuario_9f0a1e_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientopendiente',
            new_name='finanzas_mo_usuario_7ce74f_idx',
            old_name='finanzas_mo_usuario_9f0a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientopendiente',
            new_name='finanzas_mo_hash_ex_7c17c7_idx',
            old_name='finanzas_mo_hash_ex_9f0a1c_idx',
        ),
    ]
