# Generated by Django 4.2.30 on 2026-07-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0029_tarjeta_tipo_y_por_defecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tarjeta',
            field=models.ForeignKey(blank=True, help_text="Obligatorio si metodo_pago.tipo == 'CREDITO'. Recomendado/requerido si hay tarjetas de débito y metodo_pago es DEBITO. El signal de post_save valida crédito antes de generar cuotas.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='finanzas.tarjeta'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='dia_facturacion',
            field=models.IntegerField(blank=True, help_text='Día del mes en que cierra el ciclo de facturación (1-31). Solo crédito.', null=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='dia_vencimiento',
            field=models.IntegerField(blank=True, help_text='Día del mes en que vence el pago (1-31). Solo crédito.', null=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='nombre',
            field=models.CharField(help_text="Ej: 'Visa BCI', 'Cuenta RUT'", max_length=100),
        ),
    ]
