# Generated by Django 4.2.29 on 2026-03-17 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Vacaciones Llanquihue 2026'", max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('es_activo', models.BooleanField(default=False, help_text='Solo puede haber un viaje activo por familia a la vez. El frontend usa este flag para activar el Modo Vacaciones.')),
                ('color_tema', models.CharField(blank=True, help_text="Color hexadecimal para la paleta temática del viaje. Ej: '#2E86AB'.", max_length=7)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='usuarios.familia')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_planificado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.ForeignKey(help_text='Categoría presupuestada. Ej: Pasajes, Alojamiento, Comida.', on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos_viaje', to='finanzas.categoria')),
                ('viaje', models.ForeignKey(help_text='Viaje al que pertenece este ítem de presupuesto.', on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='viajes.viaje')),
            ],
            options={
                'unique_together': {('viaje', 'categoria')},
            },
        ),
    ]
