# Generated by Django 4.2.29 on 2026-03-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='archivado',
            field=models.BooleanField(default=False, help_text='Si es True, el viaje se oculta del listado principal pero no se elimina.'),
        ),
    ]
