# Generated by Django 4.2.30 on 2026-07-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacios", "0002_espacio_familia_origen"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionrespaldousuario",
            name="drive_connected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="configuracionrespaldousuario",
            name="drive_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="configuracionrespaldousuario",
            name="drive_refresh_token_enc",
            field=models.TextField(blank=True, default=""),
        ),
    ]
