# Generated by Django 4.2.29 on 2026-03-17 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nota', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Fondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor_cuota', models.DecimalField(decimal_places=6, help_text='Valor de la cuota del fondo en esta fecha. Se multiplica por el número de cuotas acumuladas para obtener el valor total.', max_digits=14)),
                ('fondo', models.ForeignKey(help_text='Fondo cuyo valor se está registrando.', on_delete=django.db.models.deletion.CASCADE, related_name='registros_valor', to='inversiones.fondo')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
