# Generated by Django 4.2.29 on 2026-03-17 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inversiones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondo',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fondos', to='usuarios.familia'),
        ),
        migrations.AddField(
            model_name='fondo',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Si es null, el fondo es compartido por toda la familia. Si tiene valor, es un fondo personal del usuario.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fondos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aporte',
            name='fondo',
            field=models.ForeignKey(help_text='Fondo al que ingresa este capital.', on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='inversiones.fondo'),
        ),
        migrations.AlterUniqueTogether(
            name='registrovalor',
            unique_together={('fondo', 'fecha')},
        ),
    ]
