# Generated by Django 4.2.29 on 2026-04-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='idioma_ui',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', help_text='Idioma preferido de la interfaz del usuario.', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='moneda_display',
            field=models.CharField(choices=[('CLP', 'CLP'), ('USD', 'USD'), ('EUR', 'EUR'), ('ARS', 'ARS'), ('PEN', 'PEN'), ('MXN', 'MXN'), ('COP', 'COP')], default='CLP', help_text='Código ISO 4217 de la moneda para visualización. Solo afecta el formato; los datos del servidor siempre están en la moneda base.', max_length=3),
        ),
        migrations.AddField(
            model_name='usuario',
            name='zona_horaria',
            field=models.CharField(default='America/Santiago', help_text='Zona horaria IANA preferida del usuario (ej: America/Santiago, Europe/Madrid). Usada en el cliente para formatear fechas y horas.', max_length=64),
        ),
    ]
