# Generated by Django 4.2.30 on 2026-07-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_idioma_ui_usuario_moneda_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='zona_horaria',
            field=models.CharField(default='America/Santiago', help_text='Zona horaria IANA preferida del usuario (ej: America/Santiago, Europe/Madrid). Usada en el cliente para formatear fechas y horas. Los workflows en .github/workflows/ usan cron UTC pensados para ejecutarse entre 02:00 y 04:00 hora local Chile (default America/Santiago); si cambias esa franja, recalcula los UTC en los YAML.', max_length=64),
        ),
    ]
